package(default_visibility = ["//visibility:public"])

licenses(["notice"])

alias(
    name = "android_28_x86",
    actual = "@android_test_support//tools/android/emulated_devices/generic_phone:android_28_x86",
)
